name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      SHOULD_RUN: ${{ secrets.RUN_TESTS }}

    steps:
    - name: Check if tests should run
      if: env.SHOULD_RUN == 'true'
      uses: actions/checkout@v2

    - name: Use Node.js
      if: env.SHOULD_RUN == 'true'
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install dependencies
      if: env.SHOULD_RUN == 'true'
      run: npm install

    - name: Run tests
      if: env.SHOULD_RUN == 'true'
      run: npm test
